### PR TITLE
Tabindex and onFocus/onBlur for any View

### PR DESCRIPTION
**Pull request by ptmt**
This is just a proposal. User should be able to set `onFocus` and `onBlur` handlers on any view and manage focused state by a keyboard using `tabIndex` property. 

Current task:
- [x] NSView doesn't respond to `tab` key, only NSControls.
- [ ] Support custom order, reverse order. 
- [ ] Cleanup

### CODE REVIEW

**Comment by ptmt** [comment]
Example: (2 <TextInput /> and 1 <View /> with `onFocus` and `onBlur` handlers to change border)
keyloop

**Comment by pvinis** [comment]
Why do custom stuff like that? When tabbing, focus should only jump between the two textfields. if the accessibility feature is set, then tabbing will cycle between the two textfields and the button. I dont think there is a need to override keyDown etc, right?

**Comment by ptmt** [comment]
@pvinis It's a proposal of two different things here. In the web browser there is an behavior that considered as expected: the ability to not use the mouse / touchpad at all while interacting with the form, including links and buttons. I'm not so sure about `keyDown` override, though. Just an implementation details. The second thing here is an ability to create custom components which could be first responders and react to focus. For example, some navigation system based on pure `<View />` (tree view for browsing files). So yeah, this is the thing where classic desktop experience meets web (electron) expectations from users.

**Comment by pvinis** [comment]
right, but since we are trying to simulate _native_ with other tech (here: web), we should respect the defaults, and change then only when its enhancing. so for the tab cycle, i think the text inputs should be the only targets, since you can press the `enter` key and the submit button would be pressed (or at least it should).
the `View`-based first responders, i think that is a change that is enhancing the default native behavior. so probably something can be done with the `acceptsFirstMouse` or an `NSResponder` to make an `NSView` with that functionality.

**Comment by ptmt** [comment]
@pvinis sure, you're right, it should only work if the user wants it working, in this case, because of `tabIndex` prop. Thank you for your advice for implementation, I hope to get time soon to continue working on this, and add another example (default / custom behavior).

**Comment by pvinis** [comment]
http://superuser.com/a/473145/90011
that is the option i meant that allows you to tab through the buttons too.

**Comment by beretboat** [comment]
Just found out that I made my self the assignee some days ago. It was a misoperation, I must have clicked some button by mistake. Sorry for the inconvenience cause.

**Comment by ptmt** [comment]
that's fine

**Comment by ptmt** [comment]
will do in the new PR

**Pull request closed without merging**
