### PR TITLE
Optional autolayout

### PR DESCRIPTION
**Pull request by ptmt**
This shouldn't break the current behavior and thus, it's fully optional and most likely will be removed in further releases.

### CODE REVIEW

**Comment by matpaul** [comment]
@ptmt Hi, any updates about this pull request ?)

**Comment by ptmt** [comment]
Do you have any problems with layout recalculating in master?

**Comment by matpaul** [comment]
There is an issue with resize, you can see it when resize window fast (for ex. Button tab) in UIExplorer

**Comment by matpaul** [comment]
Off topic question - Why Examples (SimpleChatClient) not in master ?

**Comment by ptmt** [comment]
> Off topic question - Why Examples (SimpleChatClient) not in master ?

It was hard to maintain them.

**Pull request closed without merging**
